/**
 * Polymarket V2 builder — golden signature parity tests.
 *
 * The signatures below were generated by the Python `Scripts/executor/builders.py`
 * pipeline (eth_account + EIP-712 encoder) on 06.05.2026 with the
 * deterministic inputs declared in this file. The TS path through viem
 * MUST produce byte-identical hex signatures for both POLY_DOMAIN_STANDARD
 * and POLY_DOMAIN_NEGRISK domains. Any drift here is a fatal P0 — the
 * server validates ECDSA-recover(sig) == signer, so even one bit off
 * means every order is rejected.
 *
 * The fixture private key is `0x11...11` (32 bytes of 0x11) — a public
 * test vector with no real funds attached. Do NOT rotate it without
 * regenerating the golden hashes via the same Python script.
 */

import { describe, expect, it } from 'vitest';
import { buildPolyOrder } from '../../src/builders/poly.js';
import type { Wallet } from '../../src/types/wallet.js';

// ── Deterministic fixtures ─────────────────────────────────────────

const TEST_PRIVKEY = `0x${'11'.repeat(32)}` as const;
const TEST_SIGNER = '0x19E7E376E7C213B7E7e7e46cc70A5dD086DAff2A' as const;
const FIXED_SALT = 12345678901234567890n;
const FIXED_TIMESTAMP_MS = 1730000000000n;
const FIXED_TOKEN_ID =
  '71321045679252212594626385532706912750332728571942442218381354637562416002854';

const TEST_WALLET: Wallet = {
  botId: 'bot1',
  ethAddress: TEST_SIGNER,
  canSign: true,
  signatureType: 0,
};

// ── Golden signatures from Python (06.05.2026) ─────────────────────

const PYTHON_GOLDEN_STANDARD =
  '0x1e2e6090bb34553a0455fa37d104bad5435c589c801ff2a0f5620eb874a5bddf' +
  '22073700d5dc315c27b5784d9c303ba7546d5ec3b8ad4892542add35a01902f91b';

const PYTHON_GOLDEN_NEGRISK =
  '0x6e4f184e8e88da28287c4556bbe7d9fa955f6588811b1ace85c538349a5ecf61' +
  '6ca2138c25cf4381f35b5f541b00fef67149c9e6c69d6650165d251cc76c5b071c';

// ── Tests ──────────────────────────────────────────────────────────

describe('buildPolyOrder — EIP-712 byte-identical with Python', () => {
  it('matches Python signature for POLY_DOMAIN_STANDARD', async () => {
    const built = await buildPolyOrder({
      tokenId: FIXED_TOKEN_ID,
      side: 'BUY',
      // The fixture used by Python builds makerAmount=10e6, takerAmount=20e6
      // explicitly — that's BUY at price=0.5, size=$10. We pass both axes
      // and let the builder derive identical scaled wei amounts.
      price: 0.5,
      sizeUsdc: 10,
      wallet: TEST_WALLET,
      negRisk: false,
      salt: FIXED_SALT,
      timestampMs: FIXED_TIMESTAMP_MS,
      privateKey: TEST_PRIVKEY,
    });
    expect(built.signed).toBe(true);
    expect(built.body.order.signature).toBe(PYTHON_GOLDEN_STANDARD);
  });

  it('matches Python signature for POLY_DOMAIN_NEGRISK', async () => {
    const built = await buildPolyOrder({
      tokenId: FIXED_TOKEN_ID,
      side: 'BUY',
      price: 0.5,
      sizeUsdc: 10,
      wallet: TEST_WALLET,
      negRisk: true,
      salt: FIXED_SALT,
      timestampMs: FIXED_TIMESTAMP_MS,
      privateKey: TEST_PRIVKEY,
    });
    expect(built.signed).toBe(true);
    expect(built.body.order.signature).toBe(PYTHON_GOLDEN_NEGRISK);
  });
});

describe('buildPolyOrder — invariants', () => {
  it('rejects out-of-range price', async () => {
    await expect(
      buildPolyOrder({
        tokenId: FIXED_TOKEN_ID,
        side: 'BUY',
        price: 0,
        sizeUsdc: 10,
        wallet: TEST_WALLET,
      }),
    ).rejects.toThrow(/price out of range/);
  });

  it('rejects bad side', async () => {
    await expect(
      buildPolyOrder({
        tokenId: FIXED_TOKEN_ID,
        // biome-ignore lint/suspicious/noExplicitAny: testing runtime guard
        side: 'HODL' as any,
        price: 0.5,
        sizeUsdc: 10,
        wallet: TEST_WALLET,
      }),
    ).rejects.toThrow(/side must be BUY\|SELL/);
  });

  it('leaves signature empty when wallet.canSign=false', async () => {
    const dryWallet: Wallet = { ...TEST_WALLET, canSign: false };
    const built = await buildPolyOrder({
      tokenId: FIXED_TOKEN_ID,
      side: 'BUY',
      price: 0.5,
      sizeUsdc: 10,
      wallet: dryWallet,
      privateKey: TEST_PRIVKEY,
      salt: FIXED_SALT,
      timestampMs: FIXED_TIMESTAMP_MS,
    });
    expect(built.signed).toBe(false);
    expect(built.body.order.signature).toBe('');
  });

  it('SELL side flips makerAmount/takerAmount semantics (Phase 19v19 parity)', async () => {
    const built = await buildPolyOrder({
      tokenId: FIXED_TOKEN_ID,
      side: 'SELL',
      price: 0.5,
      sizeUsdc: 10,
      wallet: TEST_WALLET,
      salt: FIXED_SALT,
      timestampMs: FIXED_TIMESTAMP_MS,
    });
    // SELL: maker gives CTF (20e6), takes USDC (10e6)
    expect(built.body.order.makerAmount).toBe(20_000_000n);
    expect(built.body.order.takerAmount).toBe(10_000_000n);
    expect(built.body.order.side).toBe(1);
  });

  it('targets POST /order URL', async () => {
    const built = await buildPolyOrder({
      tokenId: FIXED_TOKEN_ID,
      side: 'BUY',
      price: 0.5,
      sizeUsdc: 10,
      wallet: TEST_WALLET,
      salt: FIXED_SALT,
      timestampMs: FIXED_TIMESTAMP_MS,
    });
    expect(built.wouldPostUrl).toBe('https://clob.polymarket.com/order');
    expect(built.platform).toBe('polymarket');
  });

  it('produces stable canonical JSON for sign_payload', async () => {
    const a = await buildPolyOrder({
      tokenId: FIXED_TOKEN_ID,
      side: 'BUY',
      price: 0.5,
      sizeUsdc: 10,
      wallet: TEST_WALLET,
      salt: FIXED_SALT,
      timestampMs: FIXED_TIMESTAMP_MS,
    });
    const b = await buildPolyOrder({
      tokenId: FIXED_TOKEN_ID,
      side: 'BUY',
      price: 0.5,
      sizeUsdc: 10,
      wallet: TEST_WALLET,
      salt: FIXED_SALT,
      timestampMs: FIXED_TIMESTAMP_MS,
    });
    expect(Buffer.from(a.signPayload)).toEqual(Buffer.from(b.signPayload));
  });
});
